from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from tush import views
from django.conf.urls import include

urlpatterns = format_suffix_patterns([

    url(r'^companies/$',
        views.CompanyList.as_view(),
        name='company-list'),
    url(r'^companies/all/$',
        views.CompanyAllList.as_view(),
        name='company-all-list'),
    url(r'^companies/(?P<pk>[\w.]+)/$',
        views.CompanyDetail.as_view(),
        name='company-detail'),
    url(r'^companies/hist_data/(?P<ts_code>\w+)',
        views.CompanyHistData.as_view(),
        name='company-hist-data'),
    url(r'^indexes/$',
        views.IndexList.as_view(),
        name='index-list'),
    url(r'^indexes/all/$',
        views.IndexAllList.as_view(),
        name='index-all-list'),
    url(r'^indexes/(?P<pk>[\w.]+)/$',
        views.IndexDetail.as_view(),
        name='index-detail'),
    url(r'^indexes/hist_data/(?P<ts_code>[\w.]+)',
        views.IndexHistData.as_view(),
        name='index-hist-data'),

    url(r'^companies_daily_basic/$',
        views.CompanyDailyBasicList.as_view(),
        name='companydailybasic-list'),
    url(r'^companies_daily/(?P<pk>[0-9]+)/$',
        views.CompanyDailyBasicDetail.as_view(),
        name='companydailybasic-detail'),
    url(r'^indexes_daily_basic/$',
        views.IndexDailyBasicList.as_view(),
        name='indexdailybasic-list'),
    url(r'^indexes_daily_basic/(?P<pk>[0-9]+)/$',
        views.IndexDailyBasicDetail.as_view(),
        name='indexdailybasic-detail'),

    url(r'^companies_daily/$',
        views.CompanyDailyList.as_view(),
        name='companydaily-list'),
    url(r'^companies_daily/(?P<pk>[0-9]+)/$',
        views.CompanyDailyDetail.as_view(),
        name='companydaily-detail'),
    url(r'^indexes_daily/$',
        views.IndexDailyList.as_view(),
        name='indexdaily-list'),
    url(r'^indexes_daily/(?P<pk>[0-9]+)/$',
        views.IndexDailyDetail.as_view(),
        name='indexdaily-detail'),

    url(r'^funds_basic/$',
        views.FundBasicList.as_view(),
        name='fundbasic-list'),
    url(r'^funds_basic/all/$',
        views.FundBasicAllList.as_view(),
        name='fundbasic-list'),
    url(r'^funds_basic/(?P<pk>[0-9]+)/$',
        views.FundBasicDetail.as_view(),
        name='funds_basic-detail'),
    url(r'^funds_daily/$',
        views.FundDailyList.as_view(),
        name='funddaily-list'),
    url(r'^funds_daily/(?P<pk>[0-9]+)/$',
        views.FundDailyDetail.as_view(),
        name='funddaily-detail'),
    url(r'^funds_nav/$',
        views.FundNavList.as_view(),
        name='fundnav-list'),
    url(r'^funds_nav/(?P<pk>[0-9]+)/$',
        views.FundNavDetail.as_view(),
        name='fundnav-detail'),

    url(r'^funds/(?P<column>[\w.]+)/$',
        views.FundNavData.as_view(),
        name='fund-nav-data'),

    url(r'^data/(?P<column>[\w.]+)/$',
        views.CloseData.as_view(),
        name='close-data'),
    url(r'^item_hist_data/(?P<ts_code>[\w.]+)',
        views.ItemHistData.as_view(),
        name='item-hist-data'),
])