# Generated by Django 2.1.3 on 2019-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('trade_date', models.DateTimeField(null=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('pre_close', models.FloatField()),
                ('change', models.FloatField()),
                ('pct_chg', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('trade_date', models.DateTimeField(null=True)),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('pre_close', models.FloatField()),
                ('change', models.FloatField()),
                ('pct_chg', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='indextoday',
            index=models.Index(fields=['ts_code'], name='ts_code_idx'),
        ),
        migrations.AddIndex(
            model_name='companytoday',
            index=models.Index(fields=['ts_code'], name='ts_code_idx'),
        ),
    ]
