# Generated by Django 2.1.3 on 2019-09-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField()),
                ('Total_Returns', models.CharField(blank=True, default='', max_length=100)),
                ('Annual_Returns', models.CharField(blank=True, default='', max_length=100)),
                ('Benchmark_Returns', models.CharField(blank=True, default='', max_length=100)),
                ('Benchmark_Annual', models.CharField(blank=True, default='', max_length=100)),
                ('Alpha', models.CharField(blank=True, default='', max_length=100)),
                ('Beta', models.CharField(blank=True, default='', max_length=100)),
                ('Sharpe', models.CharField(blank=True, default='', max_length=100)),
                ('Sortino', models.CharField(blank=True, default='', max_length=100)),
                ('Information_Ratio', models.CharField(blank=True, default='', max_length=100)),
                ('Volatility', models.CharField(blank=True, default='', max_length=100)),
                ('MaxDrawdown', models.CharField(blank=True, default='', max_length=100)),
                ('Tracking_Error', models.CharField(blank=True, default='', max_length=100)),
                ('Downside_Risk', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('strategy',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('stock', models.FloatField()),
                ('benchmark', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='results',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.Strategy'),
        ),
    ]
