# Generated by Django 3.0.7 on 2020-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='', max_length=100)),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('fullname', models.CharField(blank=True, default='', max_length=100)),
                ('enname', models.CharField(blank=True, default='', max_length=100)),
                ('market', models.CharField(blank=True, default='', max_length=100)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('curr_type', models.CharField(blank=True, default='', max_length=100)),
                ('list_status', models.CharField(blank=True, default='', max_length=100)),
                ('list_date', models.DateTimeField(null=True)),
                ('delist_date', models.DateTimeField(null=True)),
                ('is_hs', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('fullname', models.CharField(blank=True, default='', max_length=100)),
                ('market', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=100)),
                ('index_type', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('base_date', models.DateTimeField(null=True)),
                ('base_point', models.FloatField()),
                ('list_date', models.DateTimeField(null=True)),
                ('weight_rule', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
                ('exp_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='index',
            index=models.Index(fields=['ts_code'], name='ts_code_index_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['symbol'], name='symbol_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['ts_code'], name='ts_code_company_idx'),
        ),
    ]
