# Generated by Django 2.1.3 on 2019-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('trade_date', models.DateTimeField(null=True)),
                ('close', models.FloatField()),
                ('turnover_rate', models.FloatField()),
                ('turnover_rate_f', models.FloatField()),
                ('volume_ratio', models.FloatField()),
                ('pe', models.FloatField()),
                ('pe_ttm', models.FloatField()),
                ('pb', models.FloatField()),
                ('ps', models.FloatField()),
                ('ps_ttm', models.FloatField()),
                ('total_share', models.FloatField()),
                ('float_share', models.FloatField()),
                ('free_share', models.FloatField()),
                ('total_mv', models.FloatField()),
                ('circ_mv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(blank=True, default='', max_length=100)),
                ('trade_date', models.DateTimeField(null=True)),
                ('total_mv', models.FloatField()),
                ('float_mv', models.FloatField()),
                ('total_share', models.FloatField()),
                ('float_share', models.FloatField()),
                ('free_share', models.FloatField()),
                ('turnover_rate', models.FloatField()),
                ('turnover_rate_f', models.FloatField()),
                ('pe', models.FloatField()),
                ('pe_ttm', models.FloatField()),
                ('pb', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='indexdaily',
            index=models.Index(fields=['ts_code'], name='ts_code_idx'),
        ),
        migrations.AddIndex(
            model_name='companydaily',
            index=models.Index(fields=['ts_code'], name='ts_code_idx'),
        ),
    ]
